// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'apiKey',
    appId: '1:315288722470:web:43ef13253d6c3b2c4f1ae7',
    messagingSenderId: '315288722470',
    projectId: 'aichatbot-e8930',
    authDomain: 'aichatbot-e8930.firebaseapp.com',
    storageBucket: 'aichatbot-e8930.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKVfq29x90qhG6e-K6XHfyCFUUUOg99E',
    appId: '1:315288722470:android:014bfd0f53554ecf4f1ae7',
    messagingSenderId: '315288722470',
    projectId: 'aichatbot-e8930',
    storageBucket: 'aichatbot-e8930.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSUoWJZRCwDP6zTAQo9vLwUaZ0A_7d6HY',
    appId: '1:315288722470:web:dd383cfc790021c74f1ae7',
    messagingSenderId: '315288722470',
    projectId: 'aichatbot-e8930',
    authDomain: 'aichatbot-e8930.firebaseapp.com',
    storageBucket: 'aichatbot-e8930.appspot.com',
  );
}
